# https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

github:
  description: "Apache Pekko Connectors is a Reactive Enterprise Integration library for Java and Scala, based on Reactive Streams and Apache Pekko."
  homepage: https://pekko.apache.org/
  labels:
    - pekko
    - pekko-streams
    - pekko-connnectors
    - integration
    - reactive
    - reactive-streams
    - messaging

  protected_tags:
    - "v*.*.*"

  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true

  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  true

  protected_branches:
    main:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1
    1.0.x:
      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false
        # contexts are the names of checks that must pass
        contexts:
          - Code is formatted
          - Check headers
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        required_approving_review_count: 1        

notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org
  discussions:          notifications@pekko.apache.org
