# SPDX-License-Identifier: Apache-2.0
pekko {
  loglevel = "INFO"
}

pekko.connectors.google.credentials {
  provider = google-application-default
  google-application-default {
    project-id = "pekko-connectors"
  }
}
