name: Update Dependency Graph
on:
  push:
    branches:
      - main # default branch of the project
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    if: github.repository == 'apache/pekko-connectors'    
    steps:
      - uses: actions/checkout@v4
      - name: Install sbt
        uses: sbt/setup-sbt@v1      
      - uses: scalacenter/sbt-dependency-submission@v2
