name: Headers

on:
  pull_request:

permissions: {}

jobs:
  check-headers:
    name: Check headers
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Check headers
        run: |-
          sbt \
          -Dsbt.override.build.repos=false \
          -Dsbt.log.noformat=false \
          +headerCheckAll
