name: Publish 1.1 docs

on:
  workflow_dispatch:

jobs:
  publish:
    # runs on main repo only
    if: github.repository == 'apache/pekko-connectors'
    name: Publish
    runs-on: ubuntu-20.04
    env:
      JAVA_OPTS: -Xms2G -Xmx3G -Xss2M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Build Documentation
        run: |-
          sbt "set ThisBuild / version := \"1.1.0-M1\"; docs/paradox; unidoc"

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-connectors/1.1.0-M1/
          mkdir -p target/nightly-docs/docs/pekko-connectors/1.1/
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-connectors/1.1.0-M1/docs
          cp -r docs/target/paradox/site/main/ target/nightly-docs/docs/pekko-connectors/1.1/docs
          rm -r docs/target/paradox/site/main/
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-connectors/1.1.0-M1/api
          cp -r target/scala-2.13/unidoc target/nightly-docs/docs/pekko-connectors/1.1/api
          rm -r target/scala-2.13/unidoc

      - name: Upload 1.1.x docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-connectors/1.1.0-M1 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}

      - name: Upload 1.1 docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-connectors/1.1 # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
